---
title: '@JAVA基础: 异常处理'
comments: true
categories: 开发
abbrlink: be4602f2
date: 2017-12-29 10:09:09
updated: 2018-02-08 17:33:00
tags: java
keywords:
description:
---


异常机制可以保证程序中的异常处理代码和正常业务代码分离，保证程序代码更加优雅，并可以提高程序的健壮性。

<!--more-->

## 概述

Java 的异常机制主要依赖于**try, catch, finally, throw, throws**五个关键字。

- try 关键字后紧跟一个花括号括起来的代码块，它里面放置可能引发异常的代码；
- catch 后对应异常类型和代码块，用于表明该 catch 块用于处理这种类型的代码块；
- 多个 catch 块后还可跟一个 finally块，finally 块用于回收在 try 块里打开的物理资源，异常机制会保证 finally块总被执行；
- throws 关键字主要在方法签名后使用，用于声明该方法可能会抛出的异常；
- 而 throw 可以单独作为语句使用，抛出一个具体的异常。

Java 的异常处理机制让程序具有更好的容错性，当程序出现意外情形时，系统会自动生成一个 Exception 对象来通知程序，通过在 try 块后添加多个 catch 块可以无需在处理快中使用 if、swich 判断异常类型，但依然可以针对不同的异常类型提供相应的处理逻辑，从而提供更细致、更有条理的异常处理逻辑。

如果执行 try 块里的业务逻辑代码时出现异常，系统自动生成一个异常对象，该异常对象被提交给 Java 运行时环境，这个过程被称为抛出（throw）异常。

当 Java 运行时环境收到异常对象时，会寻找能处理该异常对象的 catch 块，如果找到合适的 catch 块，则把该异常对象交给该 catch 块处理，这个过程被称为捕获（catch）异常；如果 Java 运行时环境找不到捕获异常的 catch 块，则运行时环境终止，Java 程序也将退出。

***注：try 块里声明的变量是代码块内局部变量，它只在 try 块内有效，在 catch 块中无法访问该变量。***

Java 异常捕获流程示意图如下：
![](http://ipic-markdown.oss-cn-shanghai.aliyuncs.com/blog/2017-12-28-074611.png)

一个异常捕获例子：
*（注：从 Java7开始，一个 catch 块可以捕获多种类型的异常）*

```java
Public class DivTest{

	public static void main(String[] args){
		try{
			int a = Integer. ParseInt  (args  [0]); 
			int b = Integer. ParseInt  (args  [1]); 
			int c = a/b;
			System.out.println("您输入的两个数相除的结果是：" + c);
		}catch  (IndexOutOfBoundsException | NumberFormatException | ArithmenticException ie){
			System.out.println("程序发生了数组越界、数字格式异常、算数异常之一"); 
			//捕获多种异常时，异常变量默认有 finally 修饰符
			//所以下面代码有误
			ie = new ArithementicException("test");
		}catch  (Exception e){
			System.out.println("未知异常");
			//捕获一种异常时，异常变量没有 finally 修饰符
			//所以下面代码完全正确
			e = new RuntimeException("test");
		}
	}

}
```


## 异常分类

![](http://ipic-markdown.oss-cn-shanghai.aliyuncs.com/blog/2018-02-08-Class%20Diagram3.png)

这是一个简化的Java异常层次结构示意图，需要注意的是所有的类都是从Throwable继承而来，下一层则分为两个结构，Error和Exception。其中Error类层次描述了Java运行时系统的内部错误和资源耗尽错误，这种错误除了简单的报告给用户，并尽力阻止程序安全终止之外，一般也米有别的解决办法了。

**Checked 异常和 Unchecked 异常区别？**
派生于Error或者RuntimeException的异常称为unchecked异常，所有其他的异常成为checked异常。Checked异常必须被显式地捕获或者传递，而unchecked异常则可以不必捕获或抛出。

在设计 Java 程序时，需要关注 Exception 层次结构。其又派生出两个分支，一个分支是 RuntimeException；另一个分支包含其他异常。**划分两个分支的规则是：由程序错误导致的异常属于 RuntimeException；而程序本身没有问题，但由于像 I/O 错误这类问题导致的异常属于其他异常**

派生于 RuntimeException 的异常包含下面几种情况：

- 错误的类型转换。
- 数组访问越界。
- 访问 null 指针。

不是派生于 RuntimeException 的异常包括：

- 试图在文件尾部后面读取数据。
- 试图打开一个不存在的文件。
- 试图根据给定的字符串查找 Class 对象，而这个字符串表示的类并不存在。

“如果出现 `RuntimeException` 异常，那么就一定是你的问题”是一条相当有道理的规则。应该通过检测数组下标是否越界来避免 `ArrayIndexOutOfBoundsException` 异常；应该通过在使用变量之前检测是否为 null 来杜绝 `NullPointerException` 异常的发生。

如何处理不存在的文件呢？难道不能先检查文件是否存在再打开它吗？嗯，这个文件有可能在你检查它是否存在之前就已经被删除了。因此，“是否存在”取决于环境，而不只是取决于你的代码。

Java 语言规范将派生于 Error 类或 RuntimeException 类的所有异常称为非受查（unchecked）异常，所有其他的异常称为受查（checked）异常，这是两个很有用的术语。编译器将核查是否为所有的受查异常提供了异常处理器。如果程序没有处理Checked 异常，该程序在编译时就会报错，将无法通过编译。

简单来说，Checked 异常未处理，编译时就会报错，而 Runtime 异常未处理在编译阶段是不会被发现的，只有在运行时才会被发现。

## 捕获异常

如果某个异常发生的时候没有任何地方进行捕获，那程序就会终止执行，并在控制台上打印出异常信息，其中包括异常的类型和堆栈的内容。

当 Java 运行时决定调用某个 catch 块来处理该异常对象时，会将异常对象赋给 catch 块后的异常形参，程序可通过该参数来获得异常的相关信息。所有的异常对象都包含了如下几个常用方法：

- e.getMessage()：返回该异常的详细描述字符串。
- e.getClass().getName()：得到详细的错误信息
- e.getCause()：重新得到原始异常
- e.printStackTrace()：将该异常的跟踪栈信息输出到标准错误输出。
- e.printStackTrace(PrintStream s)：将该异常的跟踪栈信息输出到指定输出流。
- e.getStackTrace()：返回该异常的跟踪栈信息。会得到 StackTraceElement 对象的一个数组，可以在程序中分析这个对象数组

## 使用 finally 回收物理资源

程序在 try 块里打开了一些物理资源（如数据库连接、网络连接和磁盘文件等），这些物理资源都必须显式回收。**Java 的垃圾回收机制不会回收任何物理资源，垃圾回收机制只会回收堆内存中对象所占用的内存。**

为了保证一定能回收 try 块中打开的资源，异常处理机制提供了 finally 块，不管 try 块中的代码是否出现异常，也不管那一个 catch 块被执行，甚至 try 块或 catch 块中执行了 return 语句，finally 块总会被执行。

在通常情况下，不要在 finally 块中使用 return 或 throw 等导致方法终止的语句，一旦在 finally 块中使用了上述的语句，将会导致 try 块、catch 块中的 return 或 throw 语句失效。系统在执行到 try 块或 catch 块中的 return 或 throw 语句时，会先去寻找是否有 finally 块，若有 finally 块，则先执行 finally 块，再跳转回 try 或 catch 块中去执行刚刚的 return 或 throw 语句，若 finally 块中有 return 或 throw 语句，则try 块、catch 块中的 return 或 throw 语句失效。

异常处理嵌套的深度没有明确的限制，但通常没有必要使用超过两层的嵌套异常处理。

Java7以后，几乎所有的“资源类”（包括文件IO 的各种类，JDBC 的connection、statement 等接口）进行了改写，改写后资源类都实现了 AutoCloseable 或 Closeable 接口，可以在 try 块后紧跟一对圆括号，将需要在程序结束后关闭资源的类放入其中，Java 会自动关闭这些资源，不再需要在 finally 块里显式关闭try 块中使用的物理资源。

## 使用 throws 声明抛出异常

throws 声明抛出的语法格式紧跟在方法签名之后，使用 throws 声明抛出的异常，表明当前方法不处理该类型的异常，将异常抛给其调用者，调用者需要用 try...catch 处理这个异常，或者继续使用 throws 将该异常抛出去给下一个上级调用者，若直到最顶级调用者，仍未处理该异常，JVM 会会打印出异常跟踪栈信息，并将程序终止。

## 使用 throw 抛出异常

如果需要在程序中手动抛出异常，则应使用 throw 语句，throw 语句抛出的不是异常类，而是一个异常实例，如 `throw new Exception("这是一条异常信息。");`，当 Java 运行时接收到开发者手动抛出的异常时，与系统自动抛出的异常一样，JVM 都会中止当前的执行刘，跳转到该异常对应的 catch 块，由该 catch 块来处理该异常。


## 自定义异常类

用户自定义异常类都应该继承 Exception 基类，若要自定义Runtime异常，则应该继承 RuntimeException 类，定义异常类时需要定义两个构造器：

- 无参构造器
- 带一个字符串参数的构造器，这个字符串将作为该异常对象的描述信息（也就是异常对象的 getMessage()方法的返回值）

```java

public class AuctionException extends Exception{
    // 无参构造器
    public AuctionException(){};
    public AuctionException(String msg){
        super(msg);
    }
}

```

企业级应用对异常的处理通常分成两个部分：

- 应用后台需要通过日志来记录异常发生的详细情况
- 应用需要根据异常向应用使用者传达某种提示

## 异常链（职责链模式）

![](http://ipic-markdown.oss-cn-shanghai.aliyuncs.com/blog/2017-12-28-163709.png)

当业务逻辑层访问持久层出现 SQLException 异常时，程序不应该把底层的SQLException异常穿到用户界面，而是应该先捕获原始异常，让后将该异常转译，抛出一个业务异常，该业务异常中包含了对用户的提示，如“系统出现异常”这类的提示。

在 JDK1.4 后，所有Throwable的子类在构造器中都可以接收一个异常实例作为参数，而不再是仅仅只能接收以个 String 参数。


## 异常跟踪栈

![](http://ipic-markdown.oss-cn-shanghai.aliyuncs.com/blog/2017-12-28-164504.png)

很多初学者一看到上图的异常信息，就会惊慌失措，其实上图的异常跟踪栈信息非常详细，第一行显示了异常的类型和异常的详细信息，接下来跟踪栈记录程序中所有的异常发生点，从上到下依次为异常的第一个触发点，直到最外层的程序入口main 方法或Thread 类的 run 方法。

举例如下：

![](http://ipic-markdown.oss-cn-shanghai.aliyuncs.com/blog/2017-12-28-164933.png)

程序在 Thread 的 run 方法中出现了 ArithmeticException异常，这个异常的源头在ThreadExceptionTest 的 secondMethod 方法，位于 ThreadExceptionTest.java 的第27行，这个异常传播到Thread 类的 run 方法就会结束（如果该异常没有得到处理，将会导致该线程被中止运行）

虽然 printStackTrace() 方法可以很方便地用于追踪异常的发生情况，可以用它来调试程序，但在最后发布的程序中，应该避免使用它；而应该对捕获的异常进行适当的处理，而不是简单地将异常的跟踪栈信息打印出来。

## 使用异常机制的技巧

**不要过度使用异常**

例子：

```java
if(!s.empty()) s.pop();
```

```java
try{
    s.pop();
}catch(EmptyStackException e){
    ...
}
```

在测试机上，前者将花费646毫秒，后者将花费 21739毫秒，捕获异常花费的时间大大超过前者。

- 异常处理机制的初衷是将不可预期异常的处理代码和正常的业务逻辑代码分离，因此绝不要使用异常处理来代替正常的业务逻辑判断。
- 异常机制的效率比正常流程的效率差。因为 Java 运行时接收到这个异常后，还需要进入相应的 catch 块来捕获该异常，再进行处理
- 异常只应该用于处理非正常的情况，不要使用异常处理来代替正常的流程控制，对于一些完全可预知、而且处理方式清除的错误，程序应该提供相应的错误处理代码，而不是笼统地称为异常。


**不要使用过于庞大的 try 块**

- 当 try 块过于庞大时，就难免在 try 后紧跟大量的 catch块才可以针对不同的异常提供不同的处理逻辑，同一个 try 块后紧跟大量的catch 块需要分析它们之间的逻辑关系，反而增加了编程的复杂性
- 正确做法是，把大块的 try 块分割成多个可能出现异常的程序段落，并把它们放在单独的try 块中，从而分别捕获处理异常

**不要忽略捕获到的异常**

- 既然已经捕获到了异常，就应该在 catch 块中对该异常做一定处理，
- catch 块为空是不可取的，最差也应该在catch 块中打印错误跟踪栈信息，最好是对异常做一定的处理，或者将该异常抛出，交给调用者处理

**在检测错误时，“苛刻”要比放任更好**
当检测到错误的时候，有些程序员担心抛出异常。在用无效的参数调用一个方法时，返回一个虚拟的数值，还是抛出一个异常，哪种处理方式更好？例如，当栈空时，`Stack.pop` 是返回一个 null，还是抛出一个异常？一般来说：在出错的地方抛出一个 `EmptyStackException` 异常要比在后面抛出一个
`NullPointerException` 异常更好。

**不要羞于传递异常**

很多程序员都感觉应该捕获抛出的全部异常。如果调用了一个抛出异常的方法，例如，FileInputStream 构造器或 readLine 方法，这些方法就会本能地捕获这些可能产生的异常。其实，传递异常要比捕获这些异常更好：

```java
pub1ic void readStuff (String fi1ename) throws I0Exception{
    InputStream in= new FileInputStream (filename);
}
```

_**即：“早抛出，晚捕获”。**_


## 参考链接

- [Java异常：选择Checked Exception还是Unchecked Exception?](http://blog.csdn.net/kingzone_2008/article/details/8535287}

取的，最差也应该在catch 块中打印错误跟踪栈信息，最好是对异常做一定的处理，或者将该异常抛出，交给调用者处理